server:
  port: 8087
  servlet:
    context-path: /api

spring:
  application:
    name: flourmo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      #      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false  # 禁用自动提交
    listener:
      ack-mode: manual_immediate

logging:
  file: 
    name: log/flourmo.log
  level:
    com:
      kinopio:
        flourmo: debug
