server:
  port: 8087
  servlet:
    context-path: /api

spring:
  application:
    name: flourmo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      #      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false  # 禁用自动提交
    listener:
      ack-mode: manual_immediate
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Ttl@20241128
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      jedis:
        pool:
          enabled: true
          max-idle: 500
          min-idle: 0
          max-active: 8
          max-wait: -1

  redis:
    #    需要持久化的，用来存放热门点击等
    app:
      host: 127.0.0.1
      password:
      database: 0
      port: 6379
      pool:
        max-idle: 500
        min-idle: 0
        max-active: 8
        max-wait: -1
      timeout: 100
---
redisson:
  address: redis://${spring.data.redis.host}:${spring.data.redis.port}
  password: ${spring.data.redis.password}
  database: ${spring.data.redis.database}
  connection-pool-size: 10
  connection-minimum-idle-size: 5
  idle-connection-timeout: 10000
  connect-timeout: 10000
  timeout: 3000 

logging:
  config: classpath:log4j2.xml
